# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimientos', '0003_auto_20171019_2041'),
        ('personas', '0004_auto_20171020_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraccionActa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fechaArchivado', models.DateField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Establecimiento')),
                ('oficialSumariante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona')),
            ],
        ),
    ]
