# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiposDeUso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipouso',
            name='medida',
            field=models.CharField(choices=[('0', 'unidad'), ('1', 'm'), ('2', 'm2'), ('3', 'm3'), ('4', 'Ha'), ('5', 'KW')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tipouso',
            name='periodo',
            field=models.CharField(choices=[('0', 'hora'), ('1', 'dia'), ('2', 'mes'), ('3', 'año')], max_length=1),
        ),
    ]
