# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20171107_2211'),
        ('comision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='reclamos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='documentos.Documento'),
            preserve_default=False,
        ),
    ]
