# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiposDocumentacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumentacion',
            options={'ordering': ['-nombre']},
        ),
    ]
