# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edicto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expediente',
            new_name='Edicto',
        ),
        migrations.RenameField(
            model_name='edicto',
            old_name='fecha_creacion',
            new_name='fechaExigencia',
        ),
        migrations.RenameField(
            model_name='edicto',
            old_name='fecha_maxima',
            new_name='fechaPublicacion',
        ),
    ]
