# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expediente',
            options={'ordering': ['-numero']},
        ),
        migrations.RenameField(
            model_name='expediente',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
    ]
