# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-06 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afluente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('caudal', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('superficie', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['-nombre'],
                'permissions': (('cargar_afluente', 'Cargar afluentes'), ('detalle_afluente', 'Ver detalle de afluentes'), ('listar_afluente', 'Listar afluentes'), ('modificar_afluente', 'Modificar afluentes'), ('eliminar_afluente', 'Eliminar afluentes')),
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('superficie', models.CharField(max_length=50)),
                ('poblacion', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('slug', models.SlugField()),
                ('protegido', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('cargar_departamento', 'Cargar deparamentos'), ('modificar_departamento', 'Modificar deparamentos'), ('detalle_departamento', 'Ver detalle de deparamentos'), ('listar_departamento', 'Listar deparamentos'), ('eliminar_departamento', 'Eliminar deparamentos')),
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('codigoCatastral', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('superficie', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona')),
            ],
            options={
                'permissions': (('cargar_establecimiento', 'Cargar establecimientos'), ('listar_establecimiento', 'Listar establecimientos'), ('detalle_establecimiento', 'Ver detalle de establecimientos'), ('modificar_establecimiento', 'Modificar establecimientos'), ('eliminar_establecimiento', 'Eliminar establecimientos')),
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codpostal', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('protegido', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Departamento')),
            ],
            options={
                'permissions': (('cargar_localidad', 'Cargar localidades'), ('modificar_localidad', 'Modificar localidaes'), ('listar_localidad', 'Listar localidades'), ('eliminar_localidad', 'Eliminar localidades')),
            },
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Localidad'),
        ),
        migrations.AddField(
            model_name='afluente',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Localidad'),
        ),
    ]
