# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localidad', '0001_initial'),
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establecimiento',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='localidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='localidad.Localidad'),
            preserve_default=False,
        ),
    ]
