# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afluente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('caudal', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('superficie', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('superficie', models.CharField(max_length=50)),
                ('poblacion', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codpostal', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Departamento')),
            ],
        ),
        migrations.RenameField(
            model_name='establecimiento',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='id',
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='codigoCatastral',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='afluente',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Localidad'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='localidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Localidad'),
            preserve_default=False,
        ),
    ]
