# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0002_auto_20171010_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimiento',
            name='id',
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='codigoCatastral',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
