# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-05 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0003_auto_20171130_0239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidad',
            options={},
        ),
        migrations.AddField(
            model_name='departamento',
            name='protegido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamento',
            name='slug',
            field=models.SlugField(default='slug-id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localidad',
            name='protegido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localidad',
            name='slug',
            field=models.SlugField(default='slug-id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='codpostal',
            field=models.IntegerField(),
        ),
    ]
