# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-13 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0004_auto_20191005_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
