# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-04 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0005_auto_20200113_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afluente',
            options={'ordering': ['-nombre'], 'permissions': (('cargar_afluente', 'Cargar afluentes'), ('detalle_afluente', 'Ver detalle de afluentes'), ('listar_afluente', 'Listar afluentes'), ('modificar_afluente', 'Modificar afluentes'), ('eliminar_afluente', 'Eliminar afluentes'))},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'permissions': (('cargar_departamento', 'Cargar deparamentos'), ('modificar_departamento', 'Modificar deparamentos'), ('detalle_departamento', 'Ver detalle de deparamentos'), ('listar_departamento', 'Listar deparamentos'), ('eliminar_departamento', 'Eliminar deparamentos'))},
        ),
        migrations.AlterModelOptions(
            name='establecimiento',
            options={'permissions': (('cargar_establecimiento', 'Cargar establecimientos'), ('listar_establecimiento', 'Listar establecimientos'), ('detalle_establecimiento', 'Ver detalle de establecimientos'), ('modificar_establecimiento', 'Modificar establecimientos'), ('eliminar_establecimiento', 'Eliminar establecimientos'))},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'permissions': (('cargar_localidad', 'Cargar establecimientos'), ('modificar_localidad', 'Modificar establecimientos'), ('listar_localidad', 'Listar establecimientos'), ('eliminar_localidad', 'Eliminar establecimientos'))},
        ),
    ]
