# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-05 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import random

class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0013_auto_20191005_1503'),
        ('users', '0002_auto_20171003_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol_ptr',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.Persona'),
        ),
    ]
