# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-04 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200904_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('listar_usuarios', 'Listar usuarios'), ('cargar_empresa', 'Cargar empresas'), ('detalle_empresa', 'Ver detalle de empresas'), ('modificar_empresa', 'Modificar empresas'), ('eliminar_empresa', 'Eliminar empresas'))},
        ),
    ]
