# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-05 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211204_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('listar_usuarios', 'Listar usuarios'), ('cargar_usuario', 'Cargar usuarios'), ('detalle_usuario', 'Ver detalle de usuarios'), ('modificar_usuario', 'Modificar usuarios'), ('eliminar_usuario', 'Eliminar usuarios'))},
        ),
    ]
