# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-06 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('es_por_canon', models.BooleanField(default=True)),
            ],
            managers=[
                ('operaciones', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ValorDeModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.PositiveIntegerField(choices=[(1, 'Diesel'), (2, 'Kw')])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['fecha'],
                'permissions': (('cargar_valor_de_modulo', 'Cargar valores de modulos'), ('modificar_valor_de_modulo', 'Modificar valores de modulos'), ('listar_valor_de_modulo', 'Listar valores de modulos'), ('eliminar_valor_de_modulo', 'Eliminar valores de modulos')),
                'get_latest_by': 'fecha',
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('operacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagos.Operacion')),
                ('fecha_desde', models.DateField()),
            ],
            options={
                'permissions': (('cargar_cobro', 'Cargar cobros'), ('recalcular_cobro', 'Recalcular cobros'), ('eliminar_cobro', 'Eliminar cobros'), ('listar_cobro', 'Listar cobros'), ('listar_todos_cobros', 'Listar todos los cobros'), ('cargar_cobro_infraccion', 'Cargar cobros de infracción')),
                'get_latest_by': 'fecha',
            },
            bases=('pagos.operacion',),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('operacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagos.Operacion')),
            ],
            options={
                'permissions': (('cargar_pago', 'Cargar pagos'), ('modificar_pago', 'Modificar pagos'), ('listar_pago', 'Listar pagos'), ('eliminar_pago', 'Eliminar pagos'), ('listar_todos_pagos', 'Listar todos los pagos'), ('cargar_pago_infraccion', 'Cargar pagos de inspección')),
            },
            bases=('pagos.operacion',),
        ),
        migrations.AlterUniqueTogether(
            name='valordemodulo',
            unique_together=set([('fecha', 'modulo')]),
        ),
        migrations.AddField(
            model_name='operacion',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Documento'),
        ),
    ]
