# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-06 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='permisos.Permiso'),
        ),
        migrations.AddField(
            model_name='cobro',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='permisos.Permiso'),
        ),
    ]
