# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_auto_20171110_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrarValorDeModulo',
            new_name='ValorDeModulo',
        ),
    ]
