# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-13 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_auto_20211206_0342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valordemodulo',
            options={'get_latest_by': 'fecha', 'ordering': ['fecha'], 'permissions': (('cargar_valor_de_modulo', 'Cargar valores de módulos'), ('modificar_valor_de_modulo', 'Modificar valores de módulos'), ('listar_valor_de_modulo', 'Listar valores de módulos'), ('eliminar_valor_de_modulo', 'Eliminar valores de módulos'))},
        ),
    ]
