# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_auto_20171121_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='valordemodulo',
            name='modulo',
            field=models.PositiveIntegerField(choices=[(1, 'Diesel'), (2, 'Kw')], default=0),
            preserve_default=False,
        ),
    ]
