# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0009_auto_20171221_2223'),
        ('pagos', '0005_auto_20171222_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='permiso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='permisos.Permiso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='permiso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='permisos.Permiso'),
            preserve_default=False,
        ),
    ]
