# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_auto_20171123_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobro',
            old_name='fecha',
            new_name='fecha_desde',
        ),
        migrations.AddField(
            model_name='cobro',
            name='fecha_hasta',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
