# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_auto_20171124_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='es_por_canon',
            field=models.BooleanField(default=True),
        ),
    ]
