# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_cobro_es_por_canon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='es_por_canon',
            field=models.BooleanField(default=True),
        ),
    ]
