# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-06-21 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0013_auto_20210111_2346'),
        ('pagos', '0011_pago_es_por_canon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('es_por_canon', models.BooleanField(default=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Documento')),
            ],
            managers=[
                ('operaciones', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='cobro',
            options={'get_latest_by': 'fecha'},
        ),
        migrations.RemoveField(
            model_name='cobro',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='cobro',
            name='es_por_canon',
        ),
        migrations.RemoveField(
            model_name='cobro',
            name='fecha_hasta',
        ),
        migrations.RemoveField(
            model_name='cobro',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cobro',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='es_por_canon',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='monto',
        ),
        migrations.AddField(
            model_name='cobro',
            name='operacion_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagos.Operacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='operacion_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagos.Operacion'),
            preserve_default=False,
        ),
    ]
