# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-04 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0012_auto_20210621_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobro',
            options={'get_latest_by': 'fecha', 'permissions': (('cargar_cobro', 'Cargar cobros'), ('recalcular_cobro', 'Recalcular cobros'), ('eliminar_cobro', 'Eliminar cobros'), ('listar_cobro', 'Listar cobros'), ('listar_todos_cobros', 'Listar todos los cobros'), ('cargar_cobro_infraccion', 'Cargar cobros de infracción'))},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'permissions': (('cargar_pago', 'Cargar pagos'), ('modificar_pago', 'Modificar pagos'), ('post_pago_nuevo', 'Post pago nuevo'), ('listar_pago', 'Listar pagos'), ('eliminar_pago', 'Eliminar pagos'), ('listar_todos_pagos', 'Listar todos los pagos'), ('cargar_pago_infraccion', 'Cargar pagos de inspección'))},
        ),
        migrations.AlterModelOptions(
            name='valordemodulo',
            options={'get_latest_by': 'fecha', 'ordering': ['fecha'], 'permissions': (('cargar_valor_de_modulo', 'Cargar valores de modulos'), ('modificar_valor_de_modulo', 'Modificar valores de modulos'), ('listar_valor_de_modulo', 'Listar valores de modulos'), ('eliminar_valor_de_modulo', 'Eliminar valores de modulos'))},
        ),
    ]
