# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-05 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_auto_20211204_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'permissions': (('cargar_pago', 'Cargar pagos'), ('modificar_pago', 'Modificar pagos'), ('listar_pago', 'Listar pagos'), ('eliminar_pago', 'Eliminar pagos'), ('listar_todos_pagos', 'Listar todos los pagos'), ('cargar_pago_infraccion', 'Cargar pagos de inspección'))},
        ),
    ]
