# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-06 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('personas', '0001_initial'),
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=20)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('motivo', models.TextField(max_length=200)),
                ('documentos', models.ManyToManyField(to='documentos.Documento')),
                ('empleados', models.ManyToManyField(to='personas.Persona')),
                ('localidades', models.ManyToManyField(to='establecimientos.Localidad')),
            ],
            options={
                'verbose_name_plural': 'Comisión',
                'ordering': ['-fechaInicio'],
                'permissions': (('cargar_comision', 'Cargar comisiones'), ('detalle_comision', 'Ver detalle de comisiones'), ('listado_comision', 'Listar comisiones'), ('modificar_comision', 'Modificar comisiones'), ('eliminar_comision', 'Eliminar comisiones')),
            },
        ),
    ]
