# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0002_comision_reclamos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'ordering': ['-fechaInicio'], 'verbose_name_plural': 'Comisión'},
        ),
    ]
