# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0002_auto_20171103_1559'),
        ('documentos', '0010_merge_20171127_1848'),
        ('personas', '0007_auto_20171121_0034'),
        ('comisiones', '0003_auto_20171121_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='comision',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='comision',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='comision',
            name='reclamos',
        ),
        migrations.AddField(
            model_name='comision',
            name='documentos',
            field=models.ManyToManyField(blank=True, null=True, to='documentos.Documento'),
        ),
        migrations.AddField(
            model_name='comision',
            name='empleados',
            field=models.ManyToManyField(to='personas.Persona'),
        ),
        migrations.AddField(
            model_name='comision',
            name='localidades',
            field=models.ManyToManyField(to='establecimientos.Localidad'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='fechaFin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='comision',
            name='fechaInicio',
            field=models.DateField(),
        ),
    ]
