# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0004_auto_20171128_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='documentos',
            field=models.ManyToManyField(blank=True, to='documentos.Documento'),
        ),
    ]
