# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-09-13 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0006_auto_20171129_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='motivo',
            field=models.TextField(default='motivo comision', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comision',
            name='nota',
            field=models.CharField(default='nota comision', max_length=20),
            preserve_default=False,
        ),
    ]
