# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-04 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0007_auto_20210913_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'ordering': ['-fechaInicio'], 'permissions': (('cargar_comision', 'Cargar comisiones'), ('detalle_comision', 'Ver detalle de comisiones'), ('listado_comision', 'Listar comisiones'), ('modificar_comision', 'Modificar comisiones'), ('eliminar_comision', 'Eliminar comisiones')), 'verbose_name_plural': 'Comisión'},
        ),
    ]
