# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
