# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-06 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, help_text='The thumbnail', null=True, upload_to='thumbnails/', verbose_name='Thumbnail')),
                ('estado', models.PositiveIntegerField(choices=[(0, 'Entregado'), (1, 'Rechazado'), (2, 'Visado')], default=0)),
                ('fecha', models.DateField()),
            ],
            options={
                'permissions': (('cargar_documento', 'Cargar documentos'), ('detalle_documento', 'Ver detalle de documentos'), ('modificar_documento', 'Modificar documentos'), ('eliminar_documento', 'Eliminar documentos'), ('cargar_expediente', 'Cargar expedientes'), ('cargar_edicto', 'Cargar edictos'), ('cargar_resolucion', 'Cargar resoluciones'), ('cargar_oposicion', 'Cargar oposiciones'), ('baja_permiso', 'Dar de baja los permisos'), ('archivar_permiso', 'Archivar los permisos'), ('cargar_acta_infraccion', 'Cargar actas de Infracción'), ('cargar_acta_inspeccion', 'Cargar actas de inspección')),
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('protegido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-nombre'],
                'permissions': (('cargar_tipo_documento', 'Cargar tipo de documentos'), ('listar_tipo_documento', 'Listar tipo de documentos'), ('modificar_tipo_documento', 'Modificar tipo de documentos'), ('eliminar_tipo_documento', 'Eliminar tipo de documentos')),
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.TipoDocumento'),
        ),
    ]
