# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='nombre',
            new_name='descripcion',
        ),
    ]
