# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_auto_20171110_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='The thumbnail', null=True, upload_to='thumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='documentos/%Y/%m/%d/'),
        ),
    ]
