# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_auto_20171117_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['-nombre'], 'permissions': (('cargar_acta_inspeccion', 'Puede cargar actas de inspeccion'),)},
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='protegido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
