# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_auto_20171123_1842'),
        ('documentos', '0005_auto_20171123_2021'),
    ]

    operations = [
    ]
