# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_auto_20171123_2140'),
        ('documentos', '0006_merge_20171123_2148'),
    ]

    operations = [
    ]
