# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_merge_20171123_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='visado',
            field=models.BooleanField(default=False),
        ),
    ]
