# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_auto_20171127_0146'),
        ('documentos', '0008_merge_20171123_2202'),
    ]

    operations = [
    ]
