# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_merge_20171127_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['-nombre'], 'permissions': (('cargar_acta_inspeccion', 'Puede cargar actas de inspeccion'), ('modificar_acta_inspeccion', 'Puede modificr actas de inspeccion'), ('eliminar_acta_inspeccion', 'Puede eliminar actas de inspeccion'), ('cargar_acta_infraccion', 'Puede cargar actas de infracción'), ('modificar_acta_infraccion', 'Puede modificar actas de infracción'), ('eliminar_acta_infraccion', 'Puede cargar eliminar de infracción'), ('cargar_reclamo', 'Puede cargar reclamos'), ('modificar_reclamo', 'Puede modificar reclamos'), ('eliminar_reclamo', 'Puede eliminar reclamos'), ('cargar_pago', 'Puede cargar pagos'), ('modificar_pago', 'Puede modificar pagos'), ('eliminar_pago', 'Puede eliminar pagos'), ('cargar_cobro', 'Puede cargar cobros'), ('modificar_cobro', 'Puede modificar cobros'), ('eliminar_cobro', 'Puede eliminar cobros'), ('cargar_oposicion', 'Puede cargar oposicion'), ('modificar_oposicion', 'Puede modificar oposicion'), ('eliminar_oposicion', 'Puede eliminar oposicion'), ('cargar_edicto', 'Puede cargar edicto'), ('modificar_edicto', 'Puede modificar edicto'), ('eliminar_edicto', 'Puede eliminar edicto'))},
        ),
    ]
