# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-04 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0013_auto_20210111_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'permissions': (('cargar_documento', 'Cargar documentos'), ('detalle_documento', 'Ver detalle de documentos'), ('modificar_documento', 'Modificar documentos'), ('eliminar_documento', 'Eliminar documentos'), ('cargar_expediente', 'Cargar expedientes'), ('cargar_edicto', 'Cargar edictos'), ('cargar_resolucion', 'Cargar resoluciones'), ('cargar_oposicion', 'Cargar oposiciones'), ('baja_permiso', 'Dar de baja los permisos'), ('archivar_permiso', 'Archivar los permisos'), ('cargar_acta_infraccion', 'Cargar actas de Infracción'), ('cargar_acta_inspeccion', 'Cargar actas de inspección'))},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['-nombre'], 'permissions': (('cargar_tipo_documento', 'Cargar tipo de documentos'), ('listar_tipo_documento', 'Listar tipo de documentos'), ('modificar_tipo_documento', 'Modificar tipo de documentos'), ('eliminar_tipo_documento', 'Eliminar tipo de documentos'))},
        ),
    ]
