# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-13 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('reporte_recaudación', 'Ver reporte de recaudación'), ('reporte_demora_por_estados', 'Ver reporte de demoras por estados de permiso'), ('reporte_comision', 'Ver reporte de comisiones')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
