# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-13 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'default_permissions': (), 'managed': False, 'permissions': (('recaudacion', 'Ver reporte de recaudación'), ('demora_por_estados', 'Ver reporte de demoras por estados de permiso'), ('comision', 'Ver reporte de comisiones'))},
        ),
    ]
