# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afluente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('caudal', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('superficie', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidad.Localidad')),
            ],
        ),
    ]
