# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afluente', '0002_auto_20171010_1334'),
        ('afluente', '0002_auto_20171010_1826'),
    ]

    operations = [
    ]
