# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afluente', '0002_auto_20171010_1334'),
        ('afluente', '0002_auto_20171010_1826'),
        ('afluente', '0002_auto_20171010_1821'),
        ('afluente', '0002_auto_20171010_0941'),
    ]

    operations = [
    ]
