# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afluente', '0003_merge_20171010_2252'),
        ('afluente', '0002_auto_20171010_1821'),
    ]

    operations = [
    ]
