# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afluente', '0003_merge_20171024_1739'),
        ('afluente', '0004_merge_20171011_1510'),
    ]

    operations = [
    ]
