# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afluente', '0005_merge_20171025_1631'),
        ('afluente', '0005_merge_20171024_1936'),
    ]

    operations = [
    ]
