# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-06 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=13, unique=True)),
                ('razonSocial', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=11)),
            ],
            options={
                'permissions': (('cargar_empresa', 'Cargar empresas'), ('detalle_empresa', 'Ver detalle de empresas'), ('listar_empresa', 'Listar empresas'), ('modificar_empresa', 'Modificar empresas'), ('eliminar_empresa', 'Eliminar empresas')),
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tipoDocumento', models.CharField(choices=[('1', 'DNI'), ('2', 'LC'), ('3', 'LE'), ('4', 'PASS'), ('5', 'CUIL')], max_length=1)),
                ('numeroDocumento', models.CharField(max_length=13, unique=True)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ['nombre', 'apellido'],
                'permissions': (('listar_persona', 'Listar personas'), ('cargar_persona', 'Cargar personas'), ('modificar_persona', 'Modificar personas'), ('detalle_persona', 'Ver detalle de personas'), ('eliminar_persona', 'Eliminar personas')),
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'rol'), (1, 'director'), (2, 'administrativo'), (3, 'inspector'), (8, 'jefedepartamento'), (4, 'chofer'), (5, 'solicitante'), (6, 'liquidador'), (7, 'sumariante')])),
            ],
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
                ('licencia', models.CharField(max_length=20)),
                ('vencimientoLicencia', models.DateField()),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
                ('legajo', models.IntegerField()),
                ('cargo', models.CharField(max_length=25)),
                ('fechaInicio', models.DateField()),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='JefeDepartamento',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Liquidador',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Sumariante',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
            ],
            bases=('personas.rol',),
        ),
        migrations.AddField(
            model_name='rol',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='personas.Persona'),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together=set([('tipoDocumento', 'numeroDocumento')]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='representantes',
            field=models.ManyToManyField(to='personas.Persona'),
        ),
    ]
