# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tipoDocumento', models.CharField(max_length=10)),
                ('numeroDocumento', models.CharField(max_length=15)),
                ('razónSocial', models.CharField(max_length=10)),
                ('dirección', models.CharField(max_length=60)),
                ('teléfono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='JefeDepartamento',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Rol')),
            ],
            bases=('personas.rol',),
        ),
        migrations.AddField(
            model_name='rol',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.Persona'),
        ),
    ]
