# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20171019_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='numeroDocumento',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='persona',
            name='razonSocial',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipoDocumento',
            field=models.CharField(choices=[('1', 'DNI'), ('2', 'LC'), ('3', 'LE'), ('4', 'PASS'), ('5', 'CUIT')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together=set([('tipoDocumento', 'numeroDocumento')]),
        ),
    ]
