# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20171020_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sumariante',
            fields=[
                ('inspector_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Inspector')),
            ],
            bases=('personas.inspector',),
        ),
        migrations.AddField(
            model_name='chofer',
            name='licencia',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chofer',
            name='vencimientoLicencia',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='cargo',
            field=models.CharField(max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='fechaInicio',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='legajo',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
