# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20171020_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'rol')], default=0),
            preserve_default=False,
        ),
    ]
