# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_auto_20171027_0238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['nombre', 'apellido']},
        ),
        migrations.AlterField(
            model_name='persona',
            name='razonSocial',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
