# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_auto_20171121_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=11),
        ),
    ]
