# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-15 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_auto_20171130_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=11)),
                ('razonSocial', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='razonSocial',
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipoDocumento',
            field=models.CharField(choices=[('1', 'DNI'), ('2', 'LC'), ('3', 'LE'), ('4', 'PASS')], max_length=1),
        ),
        migrations.AddField(
            model_name='empresa',
            name='representantes',
            field=models.ManyToManyField(to='personas.Persona'),
        ),
    ]
