# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-15 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0010_auto_20190915_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='representantes',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razonSocial',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default=2804656565, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipoDocumento',
            field=models.CharField(choices=[('1', 'DNI'), ('2', 'LC'), ('3', 'LE'), ('4', 'PASS'), ('5', 'CUIT')], max_length=1),
        ),
    ]
