# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-15 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0011_auto_20190915_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='representantes',
            field=models.ManyToManyField(to='personas.Persona'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
