# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-04 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0013_auto_20191005_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'permissions': (('cargar_empresa', 'Cargar empresas'), ('detalle_empresa', 'Ver detalle de empresas'), ('listar_empresa', 'Listar empresas'), ('modificar_empresa', 'Modificar empresas'), ('eliminar_empresa', 'Eliminar empresas'))},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['nombre', 'apellido'], 'permissions': (('listar_persona', 'Listar personas'), ('cargar_persona', 'Cargar personas'), ('modificar_persona', 'Modificar personas'), ('detalle_persona', 'Ver detalle de personas'), ('eliminar_persona', 'Eliminar personas'))},
        ),
    ]
