# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimientos', '0001_initial'),
        ('personas', '0001_initial'),
    ]

