# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-12-06 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('personas', '0001_initial'),
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'estado'), (1, 'solicitado'), (2, 'corregido'), (3, 'visado'), (4, 'completado'), (5, 'publicado'), (6, 'otorgado'), (7, 'baja'), (8, 'archivado')])),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_exp', models.CharField(max_length=15, null=True)),
                ('unidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fechaSolicitud', models.DateField()),
                ('fechaVencimiento', models.DateField(null=True)),
                ('afluente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Afluente')),
                ('documentos', models.ManyToManyField(to='documentos.Documento')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Establecimiento')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona')),
            ],
            options={
                'permissions': (('listar_permiso', 'Listar permisos'), ('cargar_permiso', 'Cargar permisos'), ('modificar_permiso', 'Modificar permisos'), ('eliminar_permiso', 'Eliminar permisos'), ('detalle_permiso', 'Ver detalle de permisos'), ('listar_documentacion_presentada', 'Listar documentación presentada'), ('visar_documentacion_solicitud', 'Visar documentacion de solicitud'), ('rechazar_documentacion_solicitud', 'Rechazar documentación de solicitud')),
            },
        ),
        migrations.CreateModel(
            name='TipoUso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('coeficiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_modulo', models.PositiveIntegerField(choices=[(1, 'Diesel'), (2, 'Kw')])),
                ('periodo', models.PositiveIntegerField(choices=[(1, 'hora'), (24, 'dia'), (720, 'mes'), (8640, 'año')])),
                ('medida', models.PositiveIntegerField(choices=[(1, 'unidad'), (2, 'm'), (3, 'm2'), (4, 'm3'), (5, 'Ha'), (6, 'KW')])),
                ('documentos', models.ManyToManyField(to='documentos.TipoDocumento')),
            ],
            options={
                'permissions': (('cargar_tipo_de_uso', 'Cargar tipos de usos'), ('detalle_tipo_de_uso', 'Ver detalle de tipos de usos'), ('listar_tipo_de_uso', 'Listar tipos de usos'), ('eliminar_tipo_de_uso', 'Eliminar tipos de usos'), ('modificar_tipo_de_uso', 'Modificar tipos de usos')),
            },
        ),
        migrations.CreateModel(
            name='Archivado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Completado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Corregido',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Otorgado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
                ('fecha_vencimiento', models.DateField()),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Publicado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
                ('tiempo', models.PositiveIntegerField()),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Solicitado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
                ('utilizando', models.BooleanField(default=False, help_text='El Solicitante esta utilizando actualmente el recurso hidrico')),
                ('oficio', models.BooleanField(default=False, help_text='Solicitud de permiso de uso de agua iniciada de oficio por la Inspección')),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Visado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
            ],
            bases=('permisos.estado',),
        ),
        migrations.AddField(
            model_name='permiso',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permisos.TipoUso'),
        ),
        migrations.AddField(
            model_name='estado',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='permisos.Permiso'),
        ),
    ]
