# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 15:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('establecimientos', '0002_auto_20171103_1559'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personas', '0004_auto_20171020_1606'),
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'estado'), (1, 'solicitado'), (2, 'visado'), (3, 'creado'), (4, 'completado'), (5, 'publicado'), (6, 'otorgado')])),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_exp', models.PositiveIntegerField(null=True)),
                ('afluente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Afluente')),
                ('documentos', models.ManyToManyField(to='documentos.Documento')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Establecimiento')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Solicitante')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('coeficiente', models.IntegerField()),
                ('periodo', models.CharField(choices=[('0', 'hora'), ('1', 'dia'), ('2', 'mes'), ('3', 'año')], max_length=1)),
                ('medida', models.CharField(choices=[('0', 'unidad'), ('1', 'm'), ('2', 'm2'), ('3', 'm3'), ('4', 'Ha'), ('5', 'KW')], max_length=1)),
                ('documentos', models.ManyToManyField(to='documentos.TipoDocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Completado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Creado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Otorgado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Publicado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
                ('tiempo', models.PositiveIntegerField()),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Solicitado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
                ('utilizando', models.BooleanField(default=False)),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Visado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
                ('fecha_visado', models.DateField()),
            ],
            bases=('permisos.estado',),
        ),
        migrations.AddField(
            model_name='permiso',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permisos.TipoUso'),
        ),
        migrations.AddField(
            model_name='estado',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='permisos.Permiso'),
        ),
        migrations.AddField(
            model_name='estado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
