# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afluente', '0002_auto_20171010_1821'),
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='afluente',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='afluente.Afluente'),
            preserve_default=False,
        ),
    ]
