# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_auto_20171103_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitado',
            name='oficio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona'),
        ),
    ]
