# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiposDeUso', '0001_initial'),
        ('edicto', '0002_auto_20171019_2041'),
        ('afluente', '0004_merge_20171011_1510'),
        ('personas', '0002_auto_20171019_2041'),
        ('establecimientos', '0003_auto_20171019_2041'),
        ('permisos', '0002_auto_20171010_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='')),
                ('visado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'estado'), (1, 'solicitado'), (2, 'iniciado'), (3, 'visado'), (4, 'creado'), (5, 'completado'), (6, 'publicado'), (7, 'otorgado'), (8, 'vencido')])),
            ],
            options={
                'get_latest_by': 'marca',
            },
        ),
        migrations.AddField(
            model_name='permiso',
            name='afluente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='afluente.Afluente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permiso',
            name='establecimiento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Establecimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permiso',
            name='numero_exp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='solicitante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='personas.Solicitante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permiso',
            name='tipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tiposDeUso.TipoUso'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Completado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Creado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Iniciado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
                ('fecha_iniciado', models.DateField()),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Otorgado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Publicado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
                ('edicto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edicto.Edicto')),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Solicitado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
                ('utilizando', models.BooleanField(default=False)),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Vencido',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
            ],
            bases=('permisos.estado',),
        ),
        migrations.CreateModel(
            name='Visado',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permisos.Estado')),
                ('fecha_visado', models.DateField()),
            ],
            bases=('permisos.estado',),
        ),
        migrations.AddField(
            model_name='estado',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='permisos.Permiso'),
        ),
        migrations.AddField(
            model_name='estado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='permisos.Permiso'),
        ),
    ]
