# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0003_auto_20171107_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipouso',
            name='documentos',
        ),
        migrations.RemoveField(
            model_name='tipouso',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tipouso',
            name='descripcion',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipouso',
            name='tipo_modulo',
            field=models.PositiveIntegerField(choices=[(1, 'Diesel'), (2, 'Kw')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipouso',
            name='coeficiente',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tipouso',
            name='medida',
            field=models.PositiveIntegerField(choices=[(1, 'unidad'), (2, 'm'), (3, 'm2'), (4, 'm3'), (5, 'Ha'), (6, 'KW')]),
        ),
        migrations.AlterField(
            model_name='tipouso',
            name='periodo',
            field=models.PositiveIntegerField(choices=[(1, 'hora'), (24, 'dia'), (720, 'mes'), (8640, 'año')]),
        ),
    ]
