# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0003_auto_20171019_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-fecha_solicitud']},
        ),
    ]
