# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_auto_20171110_1813'),
        ('permisos', '0004_auto_20171110_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipouso',
            name='documentos',
            field=models.ManyToManyField(to='documentos.TipoDocumento'),
        ),
    ]
