# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0005_tipouso_documentos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creado',
            new_name='Baja',
        ),
        migrations.AlterField(
            model_name='estado',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'estado'), (1, 'Solicitado'), (2, 'Visado'), (3, 'Documentación completa'), (4, 'Edicto publicado'), (5, 'Otorgado'), (6, 'Baja'), (1, 'solicitado'), (2, 'visado'), (3, 'completado'), (4, 'publicado'), (5, 'otorgado'), (6, 'baja')]),
        ),
        migrations.AlterField(
            model_name='solicitado',
            name='oficio',
            field=models.BooleanField(default=False, help_text='Indica si el permiso se inicia por una solicitud formal (solicitud) o una inspeccion (de oficio)'),
        ),
    ]
