# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0006_auto_20171121_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='unidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
