# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0007_permiso_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='unidad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
