# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0008_auto_20171221_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='unidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
