# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0009_auto_20171221_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'estado'), (1, 'Solicitado'), (2, 'Visado'), (3, 'Con Expediente'), (4, 'Edicto publicado'), (5, 'Otorgado'), (6, 'Baja'), (1, 'solicitado'), (2, 'visado'), (3, 'completado'), (4, 'publicado'), (5, 'otorgado'), (6, 'baja')]),
        ),
    ]
