# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0010_auto_20171123_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='fechaVencimiento',
            field=models.DateField(null=True),
        ),
    ]
