# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0011_permiso_fechavencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='fechaSolicitud',
            field=models.DateField(null=True),
        ),
    ]
