# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0013_auto_20171127_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitado',
            name='utilizando',
            field=models.BooleanField(default=False, help_text='Indica si el Solicitante esta utilizando actualmente el recurso hidrico'),
        ),
    ]
