# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-09-05 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0014_auto_20171130_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'estado'), (1, 'solicitado'), (2, 'visado'), (3, 'completado'), (4, 'publicado'), (5, 'otorgado'), (6, 'baja')]),
        ),
        migrations.AlterField(
            model_name='solicitado',
            name='oficio',
            field=models.BooleanField(default=False, help_text='Solicitud de permiso de uso de agua iniciada de oficio por la Inspección'),
        ),
        migrations.AlterField(
            model_name='solicitado',
            name='utilizando',
            field=models.BooleanField(default=False, help_text='El Solicitante esta utilizando actualmente el recurso hidrico'),
        ),
    ]
