# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-02-01 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0017_auto_20210115_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='numero_exp',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
