# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-02-26 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0018_auto_20210201_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corregido',
            name='fecha_corregido',
        ),
        migrations.RemoveField(
            model_name='visado',
            name='fecha_visado',
        ),
    ]
